# -*- coding: utf-8 -*-
"""requirementstwo.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oauDuxgdu1Bc36rf81TKLZELyqaI-Wc-
"""

streamlit
google-api-python-client
wordcloud
pandas
matplotlib